### ISSUE TITLE
Add `allowed_http_hosts = ["insecure:allow-all"]` by default for local development or as part of the CLI as optional step for `http-XYZ` template

### ISSUE THREAD

**Issue by bokjo** [fermyon/spin#1004]
Hello,

I'm going through the Advent of Spin and exploring Spin a bit.
Raising this one after a brief discussion on Discord.

The option `allowed_http_hosts = ["insecure:allow-all"]` is not obvious in the documentation, guess it can be there by default in the spin toml like `allowed_http_hosts = []` at least... or even `allowed_http_hosts = ["insecure:allow-all"]` if the `NODE_ENV === "development" for example.

```ts
const resp = await fetch(`https://${host}/lowercase`, {
        method: "POST",
        // mode: "same-origin",
        headers: {
          "Content-Type": "application/json",
        },
        body: JSON.stringify({ value }),
        // redirect: "follow",
      });
```

the fetch above fails if the url is just /lowercase  or if the scheme is not  https for deployed app.

Getting errors like this below are not helpful

```sh
Handler returned an error: Uncaught TypeError: not a function
    at <anonymous> (script.js:114)
    at call (native)
    at step (script.js:73)
    at <anonymous> (script.js)
    at <anonymous> (script.js:48)
    at Promise (native)
    at <anonymous> (script.js:49)
    at handleRequest (script.js:127)
```
```sh
Handler returned an error: Uncaught InternalError: HttpError::DestinationNotAllowed
    at fetch (sdk.js:4019)
    at <anonymous> (script.js:94)
    at call (native)
    at step (script.js:73)
    at <anonymous> (script.js)
    at <anonymous> (script.js:48)
    at Promise (native)
    at <anonymous> (script.js:49)
    at handleRequest (script.js:113)
```

This also applies to other languages as well, believe Rust returns something similar to `InternalError: HttpError::DestinationNotAllowed` as well.

**Comment by itowlson** [comment]
I'm super wary of having our templates set an "insecure" option by default.  `allowed_http_hosts = []` would be okay though, and I think others (@mikkelhegn maybe?) have suggested this too.

I agree we desperately need better errors for the various failure cases! (cf. https://github.com/fermyon/spin/issues/721).

@karthik2804 for the JS SDK - this shouldn't be an "internal error" - this is a legitimate failure mode of a HTTP request, just like a network error or timeout.

The error on scheme mismatch doesn't come from our outbound security - we only allow-list hosts (and optionally ports), not schemes.  @karthik2804 might be worth checking how the JS SDK surfaces this?

**Comment by mikkelhegn** [comment]
> allowed_http_hosts = [] would be okay though, and I think others (@mikkelhegn maybe?) have suggested this too.

Yes, for discoverability this would be a good addition. To serve local development would adding support for `localhost` in the `allowed_http_hosts` be an option?

**Comment by itowlson** [comment]
The thing that bothers me with that is that it could disguise issues you're going to hit in Cloud.  Indeed, I wouldn't be surprised if `localhost` were banned on Cloud for security reasons.

One thing that could be good is if an app tries to make a call and it's blocked is for Spin to print a tip "your app tried to reach `(address)` but it's not in your `allowed_http_hosts` list" (better wording obviously).  The trouble is how do we do that so it isn't either (a) invisible because logs aren't shown or (b) invisible because it's buried in log spew.

**Comment by itowlson** [comment]
Oh gosh, what if we could do "your app tried to reach `(address)` but it's not in your `allowed_http_hosts` list, hit Space to add it, or Esc to fail the call"... let's really mix the levels here!

**Comment by mikkelhegn** [comment]
Why make it hard? :-) Love it...

**Comment by mikkelhegn** [comment]
If it could be a one-time, at runtime exception, basically "Are you sure?" type of question... How would that work in a non-interactive setup though?

**Comment by itowlson** [comment]
It wouldn't.  I suspect we'd need to do some significant re-design so that we could interact in an interactive setting and go straight to failure in a non-interactive setting.  Not to mention that we'd need to figure out a design such that a host component could perform interaction without completely fouling up the layering, _and_ to figure out how to allow Spin to modify its `spin.toml` also without fouling up the layering, AND to either get it to pick up those changes or to modify its component definitions in sync, ALL WITHOUT FOULING UP THAT THRICE-CURSED LAYERING.

**Comment by itowlson** [comment]
#1007

**Comment by dicej** [comment]
Is there more work to be done on this besides @itowlson 's template PR above?

**Comment by itowlson** [comment]
I guess we can close this and open a new one for ~~layercrime~~ improving the reporting and updating experience.

**Comment by itowlson** [comment]
Captured layercrime ideas in #1090 so closing this one.
