### ISSUE TITLE
sdk: Pick a `rust-version` for `spin-sdk`

### ISSUE THREAD

**Issue by lann** [fermyon/spin#1059]
We can make nicer errors for people on too-old Rust versions by adding a [`rust-version`](https://doc.rust-lang.org/cargo/reference/manifest.html#the-rust-version-field) to the SDK's `Cargo.toml`.

**Comment by itowlson** [comment]
There was discussion a while back of documenting a minimum Rust version for building Spin itself, and we punted because it's not clear how we would maintain that.  This risks running into the same problem unless we accompany it with some CI that builds (a minimal consumer of?) the SDKs _using the nominated minimum version_.  So we should plan for that as part of this work too.

**Comment by lann** [comment]
That is a good idea, but we would still get incremental benefit from just adding it. If it gets out of sync at worst you'll end up with the current less-helpful errors.

**Comment by itowlson** [comment]
Core covered by #1071; moving remaining suggestion to new issue.
