### ISSUE TITLE
Should we display tags in the "templates list" UX?

### ISSUE THREAD

**Issue by fibonacci1729** [fermyon/spin#1151]
cc @itowlson

**Comment by itowlson** [comment]
My inclination is not, at least by default.  The description is meant to be the human-readable indicator; displaying tags feels like recapitulating that information in less readable form.

We could put them in `--verbose` but that would push us ever closer to the terminal width, beyond which point I'm pretty sure the table implementation would go berserk.  And there might be value in including them in the JSON format for programmatic consumers, but I'd guess most programmatic consumers would use `list --tag` rather than doing their own filtering.

**Comment by fibonacci1729** [comment]
I'm in agreement with that. I'm not  convinced that displaying tags is all that beneficial relative to the uncomfortable tradeoffs to be made to the UX. CLOSING.
