### ISSUE TITLE
Funky looking help text

### ISSUE THREAD

**Issue by fibonacci1729** [fermyon/spin#1254]
Specifically the indentation around the `registry` command.

<img width="1570" alt="Screenshot 2023-03-10 at 4 29 35 PM" src="https://user-images.githubusercontent.com/7605165/224432111-9bd23d07-3dca-4dfa-af38-f680c3ae0428.png">

**Comment by itowlson** [comment]
That seems to be how Clap likes to do long command descriptions - I added some text to `spin new` and it did the same thing.  I think the idea is that if several of your strings are long, and there wasn't an indent, then the entries would feel like a wall of text where the start of each entry was not visually obvious.

![image](https://user-images.githubusercontent.com/865538/224563779-dc7fdb2a-6677-4da7-92ba-24d6a993fc6e.png)

That said, the `registry` command has drifted out of proportion to the others in both length and detail, and needs things like the "experimental" warning removing.  So the fix is probably to prune back the registry text rather than to add delicious bacon to the other commands.
