### ISSUE TITLE
Add support for `spin up --key-value KEY,VALUE` 

### ISSUE THREAD

**Issue by macolso** [fermyon/spin#1404]
It would be nice to have parity between `spin up` and `spin cloud deploy` for the pre-seed key value feature. Today only `spin cloud deploy --key-value KEY,VALUE` works. This issue will track the work to add support for `spin up --key-value KEY,VALUE`. That way, Spin & Fermyon Cloud users who have a dependency on this feature can move their applications between environments easily.

**Comment by itowlson** [comment]
nit so we don't accidentally end up with different syntaxes: the `deploy` syntax is `KEY=VALUE`, i.e. equals sign not a comma.

**Comment by itowlson** [comment]
The existing `cloud deploy` syntax allows setting K/V pairs only in the app's default store (because cloud only has the default store).

1. For the local case, is it necessary to set pairs in non-default stores?
2. If so, what do we like as a syntax to do it?
 
The syntax needs to be unambiguous.  For example, anything along the lines of `store:key=value` runs into the problem that a key could contain the separator character, and using quotes to avoid the ambiguity could get messy because a K/V pair with spaces in it would need to be quoted already, I think, which could get messy...
