### ISSUE TITLE
Spin deploy and Spin cloud deploy seem to do the same thing

### ISSUE THREAD

**Issue by Mossaka** [fermyon/spin#1520]
I upgraded to the newly released v1.2.0 `spin` and was confused by the difference between `spin deploy` and `spin cloud deploy`. From the result, it looked like they are doing the same thing. (Just to be clear, this might be the case since v1.0 so it probably has nothing to do with v1.2 release). 

<img width="454" alt="image" src="https://github.com/fermyon/spin/assets/5447827/2f2e519e-65af-4390-abd3-2a3951041b08">

Then I checked the source code and found that `spin cloud deploy` is invoking the `spin deploy` command. This confirms that they are doing the same thing. 

Now my question is - going forward, do you plan to move `spin deploy` to `spin cloud spin`?

**Comment by itowlson** [comment]
`spin deploy` and `spin login` are aliases for `spin cloud deploy` and `spin cloud login`.  That is contractual behaviour and you can rely on them remaining aliases going forward (at least for the 1.x line).

The intent it that `spin cloud` will move out of the main binary (see https://github.com/fermyon/spin/pull/1452).  The `spin deploy` and `spin login` commands will continue to be aliases for the `cloud` subcommands - just those `cloud` subcommands will be hosted in the plugin rather than internally.

And... yes, for historic reasons the code currenly lives in `spin deploy` rather than `spin cloud deploy`.  So we could nitpick about whether `spin cloud deploy` is currently an alias for `spin deploy`!  _grin_  Really the guarantee is that `spin deploy` and `spin cloud deploy` are the same commands, regardless of where the code lives.

Hope this is clear - I'm happy to chat further if I've confused the issue even more!

**Comment by Mossaka** [comment]
Thanks for the clarification, @itowlson ! That makes sense. I will close this issue.
