### ISSUE TITLE
Cannot set environment variables for `spin watch` when starting the process

### ISSUE THREAD

**Issue by mikkelhegn** [fermyon/spin#1552]
I'm used to be able to pass an env. variable to a Spin application by setting in directly when running `spin up`, e.g., `PREVIEW_MODE=1 spin up`. This does not work if I use `spin watch`, i.e. `PREVIEW_MODE=1 spin watch`.

That would be a nice addition to `spin watch`

**Comment by itowlson** [comment]
Hmm, normally the `spin up` child process would automatically inherit the parent environment.  Not sure if `watchexec` needs that to be explicit.  I agree this should Just Work.

**Comment by itowlson** [comment]
Quick clarification @mikkelhegn - you _can't_ pass an env variable to a Spin guest just by going `PREVIEW_MODE=1 spin up`.  You have to use `--env` (which `spin watch` should accept and propagate).  I am not quite sure what application you are trying it with.  If you are trying `developer.fermyon.com`, that works because `npm run spin` propagates the env var using `spin up -env PREVIEW_MODE=$PREVIEW_MODE`.  So perhaps you need to try `PREVIEW_MODE=1` with something like `spin watch --env PREVIEW_MODE=$PREVIEW_MODE`?  If that doesn't work then it may indeed be a bug - let me know.

Environment variables set on the Spin process itself are usually stuff like CLI args e.g. `SPIN_TLS_CERT=foo SPIN_TLS_KEY=bar spin up`.  If those aren't propagating then let me know.

Otherwise, I think I need to see a bit more of your application / launch command and how you are using the EV.  Thanks!

**Comment by mikkelhegn** [comment]
Thank you for clarifying this @itowlson. I was using Bartholomew in my sample, not sure how I ended up concluding this, but just did a "barebone" Python app to test this out. Will close.
