### ISSUE TITLE
spin-sdk: duplicate symbol compilation error in Rust apps

### ISSUE THREAD

**Issue by psarna** [fermyon/spin#1602]
I have a demo project (https://github.com/psarna/country-counter-spin/) built with spin SDK for Rust, and some time between 1.0 and 1.3 it stopped compiling with:
```
$ spin build
(...)
note: rust-lld: error: duplicate symbol: spin-sdk-language-rust
```

After a short debugging sessions I figured that the symbol comes from here: https://github.com/fermyon/spin/blob/7ffe4b33b4873c8ad1363582cfe35a79530a1c33/sdk/rust/src/lib.rs#L21-L23
, and indeed, a workaround for the problem is to change my Cargo.toml dependency from:
```toml
spin-sdk = { git = "https://github.com/fermyon/spin", tag = "v1.3.0" }
```
to:
```toml
spin-sdk = { git = "https://github.com/fermyon/spin", tag = "v1.3.0", default-features = false }
```

That's enough for me to unblock the project and make it compile,  but I suppose it's still a regression? I tried compiling both with the stable toolchain (1.70), and nightly, both with updated `wasm32-wasi` target, and both fail with the same error.

**Comment by rylev** [comment]
This appears to be because the spin-sdk is being brought in twice (once by the app and once by libsql-client-rs), and thus the "spin-sdk-language-rust" symbol is being brought in twice. I think the fix is for "libsql-client-rs" to be updated to not use the "export-sdk-language" feature for its spin-sdk dependency. 

On a side note, is there a reason to use "libsql-client-rs" instead of using the sql support exposed by the Spin SDK? While we're not quite ready to call it 100% stable, you can still use it by adding the "experimental" feature to the Rust SDK. Here's an example app that uses this feature: https://github.com/rylev/spin-todo

**Comment by psarna** [comment]
ah, makes sense, thanks! This particular pet project is specifically a demo for libsql-client-rs, that's why it uses it as a dependency. I'll turn off the feature there, thanks again
