### ISSUE TITLE
iana-time-zone compile error

### ISSUE THREAD

**Issue by qtfkwk** [fermyon/spin#1709]
Hello!

Seeing this error in a component during `spin up`:

```
...
   Compiling chrono-tz v0.8.3
   Compiling iana-time-zone v0.1.57
   Compiling spin-sdk v1.4.1 (https://github.com/fermyon/spin?tag=v1.4.1#e0bd9115)
error: iana-time-zone is currently implemented for Linux, Window, MacOS, FreeBSD, NetBSD, OpenBSD, Dragonfly, WebAssembly (browser), iOS, Illumos, Android, Solaris and Haiku.
 --> /home/qtfkwk/.cargo/registry/src/index.crates.io-6f17d22bba15001f/iana-time-zone-0.1.57/src/platform.rs:6:1
  |
6 | / compile_error!(
7 | |     "iana-time-zone is currently implemented for Linux, Window, MacOS, FreeBSD, NetBSD, \
8 | |     OpenBSD, Dragonfly, WebAssembly (browser), iOS, Illumos, Android, Solaris and Haiku.",
9 | | );
  | |_^

error: could not compile `iana-time-zone` (lib) due to previous error
warning: build failed, waiting for other jobs to finish...
...
```

... that has in its Cargo.toml:

```toml
[dependencies.spin-sdk]
git = "https://github.com/fermyon/spin"
tag = "v1.4.1"
```

Spin depends on chrono 0.4 => 0.4.23 => iana-time-zone => 0.1.53

I think the fix might be to add iana-time-zone with the `fallback` feature to spin's Cargo.toml:

```toml
[dependencies.iana-time-zone]
version = "0.1.57"
features = ["fallback"]
```

Will test it and let you know...

Thanks!

---

* Spin version (`spin --version`): `spin 1.4.1 (e0bd911 2023-07-12)`
* Installed plugin versions (`spin plugins list --installed`)

    ```
    cloud 0.1.2 [installed]
    js2wasm 0.5.1 [installed]
    py2wasm 0.3.0 [installed]
    ```

**Comment by qtfkwk** [comment]
Ok... this worked and it's at least compiling now...

* Cloned the spin repo adjacent to my workspace with components

    ```bash
    cd ..
    git clone --branch v1.4.1 https://github.com/fermyon/spin.git
    ```

* Added following to `spin/Cargo.toml` *and to each component's `Cargo.toml`*

    ```toml
    [dependencies.iana-time-zone]
    version = "0.1.57"
    features = ["fallback"]
    ```

* Also changed from git/tag to path dependency (adjacent git repo clone) in components' `Cargo.toml`s:

    ```toml
    [dependencies.spin-sdk]
    #git = "https://github.com/fermyon/spin"
    #tag = "v1.4.1"
    path = "../../../spin/sdk/rust"
    ```

**Comment by qtfkwk** [comment]
Here's a ref on why adding `fallback` feature to iana-time-zone:

```rust
#[cfg(not(feature = "fallback"))]
compile_error!(
    "iana-time-zone is currently implemented for Linux, Window, MacOS, FreeBSD, NetBSD, \
    OpenBSD, Dragonfly, WebAssembly (browser), iOS, Illumos, Android, Solaris and Haiku.",
);
```

https://github.com/strawlab/iana-time-zone/blob/419aea557383abae417d7543644fe545c48a5298/src/platform.rs#L5

**Comment by qtfkwk** [comment]
This issue might be related to the latest Rust version, 1.72.0, released yesterday (?).

**Comment by vdice** [comment]
I see that the `spin-cli` and `spin-plugins` crates depend on `chrono` (and then eventually `iana-time-zone` as you've pointed out), however the `spin-sdk` doesn't.  Are you relying on one or both of the former crates in addition to `spin-sdk` in your app? 

(When I build the [http-rust template app](https://github.com/fermyon/spin/tree/main/templates/http-rust), which only brings in the `spin-sdk` crate, I don't see `iana-time-zone` in `Cargo.lock`.)

Which is to say, I think the ordering of the compilation output pasted above may be misleading; it appears to fail when compiling the spin-sdk crate, but I believe it is actually due to the `iana-time-zone` crate.  I assume you have a direct dependency on the `iana-time-zone` crate in your Cargo.toml?   Is the workaround mentioned above working well for you?

Also happy to dig in further if you'd be willing to share the app's Cargo.toml file...

**Comment by qtfkwk** [comment]
Yes... now have a direct dependency on `iana-time-zone`... before it was just chrono, but chrono doesn't specify the `fallback` feature.

Just tested it and it works fine after restoring git/tag spin-sdk dependency in components' `Cargo.toml`s. Thanks!

So final fix if anyone else has the same error... use the `fallback` feature in your component `Cargo.toml` `iana-time-zone` dependency.
