### ISSUE TITLE
`spin plugins list` does not list latest plugins

### ISSUE THREAD

**Issue by kate-goldenring** [fermyon/spin#1716]
Currently, `spin plugins list` acts as a way to both list available and installed plugins, the former being the default and the latter enabled with `--available`. However, it does not fetch latest before listing, so it does not fully act as a "search". Would it be cleaner to instead break these into two subcommands:
- `spin plugins search`: Look up available plugins
- `spin plugins list`: List installed plugins
The current flow matches `apt` while adding `search` matches the `brew` CLI.

The confusion may lie in the fact that `spin plugin list` does not fetch the latest plugins -- this can only be done with `spin plugins update`, so in that way, it does not suffice for "searching for latest plugins". We could fetch the latest plugins on list (implicit update) or fetch the latest to a tempdir to appropriately display available. However, if we do the second approach, there may be confusion with a subsequent install as the plugin wont exist in the local plugins repository.

**Comment by vdice** [comment]
+1 to breaking up into `search` and `list`, with the functionality described above.

**Comment by michelleN** [comment]
+1 to having spin plugin list only list installed plugins and creating a spin plugins search command separate

**Comment by fibonacci1729** [comment]
+1 to `search`; do we want to enable a `tag` mechanism (similar to what we do for templates) that allows search to match a set of criteria (e.g.: `spin plugin search <tag...>`)?

**Comment by itowlson** [comment]
I assume `spin plugin search` has to update the local catalogue (otherwise we have to re-download from GitHub on every search, plus @kate-goldenring's point about users trying to install a search result and not having it locally).  Is it correct to say that `search` is equivalent to the current `spin plugins update && spin plugins list` (plus optional filter)?

We could make `list` attempt an implicit update today, and could add a filter to it without a breaking change, and map a `search` command to that.  If we did that, the only breaking change would be for `list` to default to `--installed` instead of available (with `search` retaining the previously-default behaviour). 

* Does that seem like an accurate summary of the ask?
* Does it seem like a reasonable path to implementation?  It gives us most of it in 1.x with only the change of default needing a major version rev.
* Are there any other requirements around plugin sync?  For example, should we sync on install (so that installs get the latest version not just the latest synced version?)  Again it would be good to take the opportunity to think about the desired experience as a cohesive whole.

**Comment by itowlson** [comment]
Oh, one difference would be that `list` (sc. available) shows installed plugins even if they're not in the registry.  (E.g. plugins installed from files or URLs.)  This was a requested feature on `list`.  Would `search` want to revert that behaviour?
