### ISSUE TITLE
go sdk support db (mysql/pg)

### ISSUE THREAD

**Issue by Patrick0308** [fermyon/spin#1750]
Rust sdk already support mysql/pg. But go sdk haven't support db yet.

**Comment by Patrick0308** [comment]
I'm interest in it.

**Comment by itowlson** [comment]
@adamreese Would the pattern you established with the SQLite SDK fit with our BYO relational API?  If so, would it be reasonably quick to implement?

**Comment by adamreese** [comment]
They're a bit different.  With SQLite a connection to the database is opened and then closed.  MySQL and Postgres don't persist a connection between queries.  The API would need to be implemented in a different way.  We might be able to fake a "connection" and still use Go's `database/sql` interface.

**Comment by itowlson** [comment]
"BYO relational" is an informal term for "bring your own" databases, specifically Postgres and MySQL, as opposed to the "built in" SQLite database - sorry for the confusing term!

You are correct that the WIT files define the API.  And certainly Go could surface the WIT bindings directly, but they are not very friendly, because they use concepts like discriminated unions that Go doesn't have.  In fact, even the Rust SDK provides a bit of a wrapper over the raw WIT to make it more ergonomic.  Go is an even trickier case because it has a standard database API and the most ergonomic solution would be to adopt that.  @adamreese successfully did that for SQLite but his solution won't work for Postgres or MySQL.

If you're happy to work with the WIT bindings directly, you can try running the `wit-bindgen` tool, and use the generated code from that directly - it doesn't need to be packaged in the SDK.  Right now, though, I think we have to have `wit-bindgen` generate C and then use cgo (this is part of why we have been holding off) - if this is of interest then we can provide more detailed information and guidance.  There is work in progress to have `wit-bindgen` generate Go directly, at which point generating your own client should become a lot more practical.  #1630 is where that work is happening.

(I'm still not sure if we will provide official wrappers after #1630, because an _idiomatic_ SDK is non-trivial for the reasons @adamreese describes, and if we shipped a non-idiomatic one we'd be committing to sticking with it for a potentially long period.)

I hope that clarifies the problems and opportunities - do let us know if you're interested in working something up from the WIT files!

**Comment by Patrick0308** [comment]
Thanks for your reply! I think I get it. Adopting go's standard database API is cool!! May be I can implement it. 

> We might be able to fake a "connection" and still use Go's database/sql interface.

This way sounds good.

**Comment by adamreese** [comment]
Implemented in https://github.com/fermyon/spin/pull/1794 and https://github.com/fermyon/spin/pull/1922
