### ISSUE TITLE
spin plugin list showing two of the same version of cloud plugin installed

### ISSUE THREAD

**Issue by michelleN** [fermyon/spin#1805]
I'm currently making changes to cloud plugin and so things are a little odd on my dev machine but it seems like this shouldn't be allowed regardless:

```
$ spin plugin list
check-for-update 0.0.1
check-for-update 0.1.0
cloud 0.1.0
cloud 0.1.1
cloud 0.1.2
cloud 0.2.0 [installed]
cloud 0.2.0 [installed]
```

**Comment by itowlson** [comment]
That does seem weird.  What's in your plugins directory?

**Comment by michelleN** [comment]
@itowlson Embarrassingly, I don't remember how to access my plugins directory. Where is it located?

**Comment by itowlson** [comment]
@michelleN On Linux, the plugins directory is at `~/.local/share/spin/plugins`.  On Mac, I think it would be at `~/Library/Application Support/spin/plugins` but I might be wrong!

**Comment by michelleN** [comment]
Thanks! It ended up being `/Users/<username>/Library/Application\ Support/spin/plugins`

**Comment by michelleN** [comment]
```
/Users/michelle/Library/Application Support/spin/plugins/
├── cloud
│   └── cloud
├── js2wasm
│   ├── js2wasm
│   └── js2wasm.license
├── manifests
│   ├── cloud.json
│   ├── js2wasm.json
│   ├── pluginify.json
│   └── py2wasm.json
├── pluginify
│   └── pluginify
└── py2wasm
    ├── py2wasm
    └── py2wasm.license
```

**Comment by itowlson** [comment]
The plugins directory also contains a hidden `.spin-plugins` directory which contains a snapshot of the registry.  My guess is that 0.2.0 exists in both that snapshot _and_ in your installed plugins (`manifests`) directory, but has different manifests (because of cloud plugin local install).  And then `spin plugins list` sees that 0.2.0 is installed and marks _all_ the 0.2.0s installed maybe?

I'm still a bit surprised it can get into this state though.  Usually when you do a `spin plugin install` and the version number is already installed it says "already installed" and nopes out.  This is why `spin pluginify --install` does an uninstall-reinstall cycle.  Can you remember how you installed the cloud plugin that you were working on?

**Comment by karthik2804** [comment]
Does this have anything to do with this? https://github.com/fermyon/cloud-plugin/pull/111

**Comment by vdice** [comment]
> Does this have anything to do with this? https://github.com/fermyon/cloud-plugin/pull/111

Ah good call @karthik2804 -- that's probably it.

**Comment by itowlson** [comment]
I'm a bit sceptical.  `spin plugins list` doesn't use the binary version, only the version in the plugin manifest, which was at 0.3 at that release.

**Comment by vdice** [comment]
I'm now thinking it is an effect from using the pluginify plugin to install the... plugin.

When I install from the plugin manifest, all appears well, but when I install from a local build via `spin pluginify --install`, I see the duplicated entries:

```
$ spin plugins install --url https://github.com/fermyon/cloud-plugin/releases/download/v0.3.0/cloud.json
Are you sure you want to install plugin 'cloud' with license Apache-2.0 from https://github.com/fermyon/cloud-plugin/releases/download/v0.3.0/cloud-v0.3.0-macos-aarch64.tar.gz? yes

Plugin 'cloud' was installed successfully!

Description:
	Commands for publishing applications to the Fermyon Cloud.

Homepage:
	https://github.com/fermyon/cloud-plugin

$ spin plugin list --filter cloud
cloud 0.1.0
cloud 0.1.1
cloud 0.1.2
cloud 0.2.0
cloud 0.3.0 [installed]

$ spin pluginify -i
Plugin 'cloud' was installed successfully!

Description:
	Commands for publishing applications to the Fermyon Cloud.

Homepage:
	https://github.com/fermyon/cloud-plugin

$ spin plugin list --filter cloud
cloud 0.1.0
cloud 0.1.1
cloud 0.1.2
cloud 0.2.0
cloud 0.3.0 [installed]
cloud 0.3.0 [installed]
```

**Comment by itowlson** [comment]
Wild.  `pluginify --install` uninstalls any existing installed plugin before installing the dev one.  And all it does is call `spin plugin uninstall` followed by `spin plugin install -f` - it's not going behind the system's back.

But yeah... I see it.  And something is odd because you're seeing 0.3.0 whereas `spin-pluginify.toml` still says 0.2.0 https://github.com/fermyon/cloud-plugin/blob/main/spin-pluginify.toml

Anyway now I can see it I can take a look.  Thanks for the detective work @vdice!

**Comment by vdice** [comment]
> But yeah... I see it. And something is odd because you're seeing 0.3.0 whereas spin-pluginify.toml still says 0.2.0 https://github.com/fermyon/cloud-plugin/blob/main/spin-pluginify.toml

Oh sorry, I was futzing with the version locally when testing.  You're right, it was still 0.2.0 in source.  (Will be updated in https://github.com/fermyon/cloud-plugin/pull/117)

**Comment by itowlson** [comment]
Okay, what is happening is this:

* There are two versions both called 0.2.0: the dev version (installed from file) and the released version (not installed, but known about from the registry).
* When we run `spin plugins list`, it enumerates both installed and registry plugins.  This means we get two `cloud 0.2.0` plugins, one on the installed list and one on the registry list.
* As part of enumerating the registry plugins, we try to determine which are installed.  (Originally, `spin plugins list` was written to be registry only, but an influential Danish user found it surprising that a plugin appeared on the installed list but not on the "full" list.)  This is done by looking to see if there is one in the installation store with a matching name and version.  So the registry 0.2.0 gets marked as installed because it's matched by the installed dev 0.2.0.
* We then reconcile the installed and registry lists by matching on _manifest equality_.  So the registry 0.2.0 and installed 0.2.0 are correctly identified as distinct.

I am guessing the correct outcome is that we print `cloud 0.2.0` twice, once as installed and once not?  If so, it should be a relatively simple fix to make the "is it installed" check look at manifest equality.

If we prefer to print `cloud 0.2.0` only once (and as installed), we instead change reconciliation to look at only name and version.  Let me know if you prefer this, otherwise I'll do per the previous para.

https://github.com/fermyon/spin/pull/1613
