### ISSUE TITLE
Add console logging when using remote-llm

### ISSUE THREAD

**Issue by mikkelhegn** [fermyon/spin#1850]
When using a remote-llm configuration, it would be great if at `spin up` Spin would print information that the runtime-config has been loaded and is being used. There is currently no validation locally that you are using a remote-llm implementation.

Whether there should also be logs for each request (infer and embedding) could also be a consideration. E.g., (`Redirecting infer call to https://xxx`)

Not sure if the first suggestion above, about printing info about what runtime-config is being used, is generally useful for any runtime config being parsed at `spin up`.

**Comment by itowlson** [comment]
Those startup messages are usually for things that are actionable (this is where you can find your data, these are the URLs for your components).  I'm reluctant to include "hi, you have indeed turned on the setting that you intended to turn on" in the startup message.  We already print a _lot_ of stuff at startup and I don't know about you but my eyes now slide over all of it except the clickable URLs.

I do get that you want feedback if you forgot to apply your runtime config file, but I think we risk losing that feedback in startup message noise.  It would be good to try to think of other ways to present it.

For example, what if we put a sloth guard around _local_ LLM.  So that if a local LLM request took more than, say, 2 seconds, we printed something similar to our "debug builds are dog slow, use release instead" message.

**Comment by itowlson** [comment]
"Local inferencing may take a few minutes because of your puny GPU. Click here to shop Nvidia A100" - rejected sloth message

**Comment by mikkelhegn** [comment]
In my particular case, I was doing embeddings, and they are fairly quick locally, but the only way to figure out if the configuration worked, was to look if the cloud app had received any requests.

I agree with this statement "my eyes now slide over all of it except the clickable URLs", but that's only in the case where I'm not looking for something particular. I still think at least an acknowledgement of what runtime config was loaded would be great.

I assume the behavior today is that if it works, nothing gets printed.

**Comment by itowlson** [comment]
We could and probably should log remote requests, at `info` or `debug` level - would that address your "figure out if the configuration worked" requirement?  (In that you would see the evidence of the requests locally.)

By "an acknowledgement of what runtime config was loaded" are you thinking something like "Using runtime configuration from /mikkels/fancy/setup.toml"?  That could be useful if the runtime config were coming from an environment variable.

**Comment by mikkelhegn** [comment]
> We could and probably should log remote requests, at info or debug level - would that address your "figure out if the configuration worked" requirement? (In that you would see the evidence of the requests locally.)

👍🏻 

> By "an acknowledgement of what runtime config was loaded" are you thinking something like "Using runtime configuration from /mikkels/fancy/setup.toml"? That could be useful if the runtime config were coming from an environment variable.

This is probably another issue, but something like:

```
Using [llm_remote] and [key_value_store.remore_redis] runtime-config from /mikkels/fancy/setup.toml
```
That level of detail I think would be a good balance.
