### ISSUE TITLE
Rust SDK: guest panic when client cancels streaming response

### ISSUE THREAD

**Issue by itowlson** [fermyon/spin#1938]
I wrote this test code to cement my understanding of streaming responses:

```
use futures::SinkExt;
use spin_sdk::http_component;

/// A simple Spin HTTP component.
#[http_component]
async fn handle_stmtest(_req: spin_sdk::http::IncomingRequest, response_out: spin_sdk::http::ResponseOutparam) {
    let response = spin_sdk::http::OutgoingResponse::new(
        200,
        &spin_sdk::http::Fields::new(&[("content-type".to_string(), b"text/plain".to_vec())]),
    );
    let mut body = response.take_body();
    
    spin_sdk::http::ResponseOutparam::set(response_out, Ok(response));

    for i in 1..100 {
        let payload = format!("Hello {i}\n");
        if let Err(e) = body.send(payload.into()).await {
            eprintln!("Error sending payload: {e}");
        }
        std::thread::sleep(std::time::Duration::from_millis(100));
    }
}
```

It worked great!

However, I noticed that when I curled the endpoint, then used Ctrl+C to stop curl because I didn't need to watch _all_ the way, Spin printed this message:

```
Error sending payload: I/O error
thread '<unnamed>' panicked at 'start_send called without poll_ready being called first', /home/ivan/.cargo/registry/src/index.crates.io-6f17d22bba15001f/futures-util-0.3.28/src/sink/unfold.rs:62:21
```

Is this expected?  Or is it because I'm doing things the wrong way?

**Comment by tschneidereit** [comment]
@rylev and @dicej, can you comment on what's going on here?

**Comment by dicej** [comment]
This definitely looks like a bug.  Not sure if it's in Spin or `wasmtime-wasi`, but I can take a look either way.

**Comment by dicej** [comment]
@itowlson You can fix this by adding a `break` statement immediately after the `eprintln!` line.  Otherwise, you loop again and try to send another payload, and the `Sink` you're writing to really doesn't like that.

Specifically, the code you're hitting is https://docs.rs/futures-util/0.3.28/src/futures_util/sink/unfold.rs.html#62, where the `Sink` has been put into an unusable state after reporting the error and can't do anything but panic if you try to use it again.  It would be nice if it returned a `Result::Err` instead of panicking, but it can't really do that because the error type is generic, so it has no way of creating instances of it.  We could do better in our SDK code by wrapping the `Sink` returned by `unfold` in something that handles use-after-error more gracefully; not sure how much work that would be, though.

**Comment by dicej** [comment]
To conclude: I don't think it's really a _bug_ that there's a panic if you keep trying to write to a `Sink` that's already reported an error, but the ergonomics could perhaps be improved.

**Comment by itowlson** [comment]
@dicej You are absolutely right - the panic is on the _next_ trip around the loop _after_ the failed `send`.  I'll aim to reflect this in samples and docs.  Thanks!
