### ISSUE TITLE
Outbound Redis: not always deny by default

### ISSUE THREAD

**Issue by vdice** [fermyon/spin#1979]
https://github.com/fermyon/spin/pull/1933 added logic intended to deny outbound requests to redis for apps using the v2 manifest, unless the host is explicitly allowed via `allowed_outbound_hosts` config.

Indeed, this is the case for some apps, eg the [rust-outbound-redis](https://github.com/fermyon/spin/tree/main/examples/rust-outbound-redis) example.

However, other apps _don't_ see the same deny-by-default behavior.  This can be reproduced via the [tinygo-outbound-redis app](https://github.com/fermyon/spin/tree/main/examples/tinygo-outbound-redis) (you may need to remove the `allowed_outbound_hosts` configuration to repro if it has been applied via https://github.com/fermyon/spin/pull/1978)

**Comment by lann** [comment]
The intention was to treat the absence of `allowed_outbound_hosts` as "allow all" for backward compatibility, at least for now.

**Comment by itowlson** [comment]
I thought that was only for v1 _manifests_ (because if you were updating the manifest you could add the allow at that point).  Are we doing allow-all for v1 SDKs in v2 manifests as well?

**Comment by vdice** [comment]
Even after https://github.com/fermyon/spin/pull/1987, I'm still seeing the following inconsistency between outbound-mysql/pg behavior.

Take [rust-outbound-mysql](https://github.com/fermyon/spin/tree/main/examples/rust-outbound-mysql) and [tinygo-outbound-mysql](https://github.com/fermyon/spin/tree/main/examples/tinygo-outbound-mysql) (both now on v2 manifest):

- With `allowed_outbound_hosts=["mysql://127.0.0.1"]`: both behave as expected (requests allowed)
- With `allowed_outbound_hosts=[]`: both behave as expected (requests denied)
- With no `allowed_outbound_hosts` config: rust denies by default, tinygo allows

I'm not sure if this is expected given current conditions, etc, but thought I'd double check.

**Comment by rylev** [comment]
This is the currently expected behavior. deny-by-default is controlled by which interfaces you use. Rust uses the v2 interfaces and thus always respects `allowed_outbound_hosts`. Go uses the v1 interfaces and thus only respects `allowed_outbound_hosts` if its explicitly set.

The thought behind this was we don't want to break old apps - i.e., if it worked in Spin 1.0, it should work in Spin 2.0.

One potential improvement here would be to only do allow-by-default semantics if the user uses v1 interfaces *and* v1 manifests. Thus any update (either by using any SDK that uses v2 interfaces or by upgrading to manifest v2) would lead to deny-by-default semantics. Thoughts?

**Comment by vdice** [comment]
Closed by https://github.com/fermyon/spin/pull/2004
