### ISSUE TITLE
Rust template 2.1 fails on Windows

### ISSUE THREAD

**Issue by itowlson** [fermyon/spin#2190]
Reported by a Discord user (https://discord.com/channels/926888690310053918/1186493596501803059/1186700173397721122).

Follow these steps _on Windows_ (it works fine on Linux):

1. Download and unzip Spin 2.1 from the GH release page, and install the 2.1 templates.

2. Create an application using the `http-rust` template.  The `Cargo.toml` looks like this:

```toml
[package]
name = "spin21test"
authors = ["itowlson <ivan.towlson@fermyon.com>"]
description = ""
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
anyhow = "1"
spin-sdk = { git = "https://github.com/fermyon/spin", tag = "v2.1.0" }

[workspace]
```

3. Run `spin build`.

**Expected behaviour**

It builds.

**Actual behaviour**

A slew of errors, mostly "failed to resolve/cannot find type", but the first of which is:

```text
error: expected `world`, `interface` or `use`, found '.'
            --> C:\Users\ivan\.cargo\git\checkouts\spin-91500438ac5656d2\4ca3a56\sdk\rust\./wit:1:1
             |
           1 | ../../wit
             | ^
  --> C:\Users\ivan\.cargo\git\checkouts\spin-91500438ac5656d2\4ca3a56\sdk\rust\src\lib.rs:24:5
   |
24 | /     wit_bindgen::generate!({
25 | |         world: "platform",
26 | |         path: "./wit",
27 | |     });
   | |______^
```

If I change the SDK reference to the `crates.io` reference (`spin-sdk = "2.1"`) it works fine; but that is not what the template uses.  (Although they should, once we get the scripts properly wrangled!)

**Comment by ogghead** [comment]
I was able to reproduce by following the steps given (thank you!), and I was also able to reproduce the errors by building Spin directly on Windows with `make build`

Changing `path: "./wit"` to `path: "../../wit"` [on this line](https://github.com/fermyon/spin/blob/main/sdk/rust/src/lib.rs#L26) referenced by the build error allowed my local build to succeed. I did not verify whether this change builds on Unix systems though. I do not have context on the [wit](https://github.com/fermyon/spin/blob/main/sdk/rust/wit) file currently used as an intermediate - let me know if there is a reason that is needed! Otherwise, I am happy to publish a PR for this change tomorrow after the 9-5!

I see that Windows *is* added to the [build CI here](https://github.com/fermyon/spin/blob/main/.github/workflows/build.yml#L120) - feels like this *should* already be caught in the CI step

**Comment by itowlson** [comment]
Adding this to the 2.2 milestone as a reminder to wrangle the scripts so the released templates reference `crates.io` instead of GH (which appears to fix this).

Although it would still be good to also fix on main, so that Windows folks could use canary templates.  @fibonacci1729 are you the knowledgeable person for the Rust SDK WIT stuff?

**Comment by itowlson** [comment]
My guess would be that CI runs against the local SDK (path reference) rather than the remote SDK (git reference), I believe that Windows + Git + symlinks is a whole exciting world of hurt that Windows + symlinks alone is not.  (Cf. the lengthy, nuanced. and occasionally terrifying answers on [this SO post](https://stackoverflow.com/questions/5917249/git-symbolic-links-in-windows/59761201#59761201) (although the post itself is not directly relevant to this situation).)

(Which is presumably why `crates.io` is fine - I'm guessing in that case the symlink is followed at publish time, so that when Windows downloads from `crates.io` the files are packaged in the right place.)

**Comment by vdice** [comment]
> Worst-case scenario here if we can't address the above would be to just (yet-again) create another copy of the wits into sdk/rust..... cc/ @vdice if you have any thoughts.

I don't have any brighter ideas than this for unblocking Windows users when using the `"main"` git ref.

**Comment by vdice** [comment]
Note: with the forthcoming 2.2.0 release and thereafter, the Rust templates will use crate references rather than git (ref https://github.com/fermyon/spin/pull/2221).  This should fix the issue for Windows users.

**Comment by itowlson** [comment]
I've marked the 2.2 work involved as Done, but I'm leaving this open until 2.2 ships so that 2.1 users can find it!
