### ISSUE TITLE
Cannot pass trigger specific flags on up in multi trigger app

### ISSUE THREAD

**Issue by karthik2804** [fermyon/spin#2251]
I have an app that uses both a redis and a HTTP component. I was trying to set the HTTP listener to run on `3001` instead of `3000` by passing in.

```bash
spin up --listen localhost:3001
```

which results in an error as the redis trigger does not recognize the flag.  

```bash
spinrelease up --listen localhost:3001   
error: Found argument '--listen' which wasn't expected, or isn't valid in this context
```

Flags that are common like `--log-dir` continue to work.  

I am not exactly sure what the solution would be to this. One potential idea I can think of is that when multiple triggers are present spin can optionally parse arguments something along the lines of `--http-trigger="--listen localhost:3001" ` and only pass the argument to the HTTP trigger. and anything not in those specific arguments gets passed to both?

**Comment by radu-matei** [comment]
As a user, I would expect passing the `--listen` flag to continue to work and to apply to the HTTP trigger, but not apply to the Redis trigger.

**Comment by itowlson** [comment]
The least worst short-term solution may be simply to have triggers ignore unknown flags, although this does run us into the problem that `spin up --lsiten` would now silently discard and give unexpected default behaviour.  (For a nastier example, consider the TLS flags.)

Longer term we could consider some way for `up` to interrogate triggers about which flags they support and filter (or error) accordingly.  This would also help to construct unified help text (instead of repeating the help text for each trigger).

**Comment by itowlson** [comment]
Semi-related: at some point, we may have a disambiguation issue, e.g. websocket `--listen` vs HTTP `--listen`.  (Please don't nitpick the example - I know about the relationship between web sockets and HTTP - it was just easier than making up two imaginary triggers that legitimately used the same flag name.)

**Comment by lann** [comment]
We have a parallel problem with validating trigger config. Maybe the trigger plugin "interface" should include a mechanism for trigger executor binaries to describe their own config schema and arguments.
