### ISSUE TITLE
Spin apps are no longer allowed to set host headers with Wasmtime 21.0.1

### ISSUE THREAD

**Issue by mikkelhegn** [fermyon/spin#2575]
Using the Canary version of Spin, a guest (Spin component), is no longer able to set the host header on outbound http requests.

This change in Wasmtime is what impacts this: https://github.com/bytecodealliance/wasmtime/pull/7905. It was incorporated in Spin with Wasmtime 21.0.1 https://github.com/fermyon/spin/pull/2538.

Currently looking in to a potential update to Wasmtime to relax and still allow host headers to be set from the guest.

**Comment by lann** [comment]
There aren't many reasons to set a `host` header manually so I'm inclined to wait for someone to bring this up as an actual issue before suggesting an upstream change.

**Comment by mikkelhegn** [comment]
@karthik2804 - I know you noticed this working on the new JS SDK. Can you please bring up here what the scenario where this was encountered is?

**Comment by karthik2804** [comment]
I was working on getting the `s3` client to work and ran into issues because StarlingMonkey was originally setting the host header and it caused  duplicate headers and when I tried running against canary, I got an error about `failed to clone headers` which was due to the failure to create the resource but that has now been fixed in StarlinMonkey.

**Comment by lann** [comment]
> StarlingMonkey was originally setting the host header

To be clear: this was _not_ released code?

**Comment by karthik2804** [comment]
@lann no it is not released code, I have been building of a PR branch.

**Comment by mikkelhegn** [comment]
Thx for the clarifications. I will close this issue as will-not-fix.
