### ISSUE TITLE
`spin login` keeps asking for one-time code after authorizaton

### ISSUE THREAD

**Issue by me-diru** [fermyon/spin#2597]
I see there's `spin login --list` that gives `(default)` as output, and `--status` gives the token information. I don't know the ideal behavior if one has already logged in. Spin CLI and Fermyon Cloud seem unaware of each other, as the login flow is repeated with requests for authorization from an authorized account.

* Spin version (`spin --version`)
spin 2.5.1 (cba6773 2024-05-14)

* Installed plugin versions (`spin plugins list --installed`)
stalled
cloud 0.8.0 [installed]
cloud-gpu 0.1.0post.1713204340 [installed]
js2wasm 0.6.1 [installed]
py2wasm 0.3.2 [installed]

**Comment by itowlson** [comment]
Can you be more specific about what you are doing and what you are seeing?  It _sounds_ a bit like "if I'm already logged in to Fermyon Cloud and I run `spin cloud login` again, then (some sort of infinite loop???)"...?

**Comment by me-diru** [comment]
Ahh, my bad. So it is not entirely a loop per se. 
I had two questions:

1) I am curious to know if spin CLI  should be asking for a one-time passcode if the device is already authorized by Fermyon Cloud.  Is it because one can authorize a device from more than one account or maybe a token? 

2) The loop part is, even though the device is already authorized. When we attempt to authorize again from the same account in Fermyon Cloud, neither the device(CLI) nor Fermyon Cloud acknowledges `this device is already authorized` and instead notes it down as a new authorization by "Device authorized!"? 

Maybe mentioning a list of the existing logins available before waiting for authorization or not attempting for authorization if already device is already authorized might be better?

I hope it makes sense :D

**Comment by itowlson** [comment]
I am not sure what the issue is here.  The flow is:

* The user asks to log in
* We present a link and a one-use code
* The user opens the link, pastes the one-use code and confirms authorisation
* The browser shows "authorised" and the CLI shows "authorised" and exits

I _think_ your proposal is that, when the user asks to log in, we should determine if the device is already authorised and not expired, and if so, tell the user that and not do the rest of the process.  The trouble with that is: what if we get it wrong?  What if the CLI thinks the authorisation is still current, but the cloud doesn't?  Now you have prevented the user from logging in!

Instead, we take the simple approach: you ask to log in, we re-log you in, you know you are good to go.  There's no loop here, the user isn't stuck in a repeated process of "it keeps asking for a one-time code."  It only goes into the login process when you ask it to.

**Comment by itowlson** [comment]
By the way my usual workflow with cloud commands is `spin cloud do the-thing`, and if I'm logged in then it does the thing, and if I'm not then it yells at me to login, so I log in and repeat the command.  I can imagine if someone is proactively logging in _before_ running a command then it might be nice to elide unnecessary re-authorisations, but I am not sure it's worth it for the problems of "I really need you to log me in no matter what your token cache says."  _grin_

**Comment by me-diru** [comment]
True, that makes sense! It is deterministic in terms of the attempt to log the user in _regardless_ of whether they are already logged in or not, because the user requested to log in through `spin cloud login`. 

I guess the user will not attempt to log in unless their token has expired.

**Comment by me-diru** [comment]
I agree,
