### ISSUE TITLE
spin can not login docker private registry while docker login success

### ISSUE THREAD

**Issue by xiaocode** [fermyon/spin#2609]
Do any of the following links help with your problem?

I create local registry with k3d in my ubuntu,But I can not use spin to login the registry,It output:
```
Error: cannot log in to the registry

Caused by:
      cannot authenticate as admin to registry k3d-registry.localhost:5000: http transport error: error sending request for url (https://k3d-registry.localhost:5000/v2/): error trying to connect: error:0A0000C6:SSL routines:tls_get_more_records:packet length too long:ssl/record/methods/tls_common.c:654:, error:0A000139:SSL routines::record layer failure:ssl/record/rec_layer_s3.c:645:

```
But when I use docker login. it output "Login Succeeded"
How can I solve this?

If you still see a bug or problem, please let us know:

* Spin version (`spin --version`)
spin 2.5.1 (cba6773 2024-05-14)
* Installed plugin versions (`spin plugins list --installed`)
cloud 0.9.0 [installed]
js2wasm 0.6.1 [installed]

**Comment by xiaocode** [comment]
After I clone the latest spin repo and build, I got different response:
```
Error: cannot log in to the registry

Caused by:
      cannot authenticate as admin to registry docker.registry.local:5000: http transport error: error sending request for url (https://docker.registry.local:5000/v2/): error trying to connect: error:0A00010B:SSL routines:ssl3_get_record:wrong version number:../ssl/record/ssl3_record.c:354:
```
Spin version:
spin 2.7.0-pre0 (7833e71a 2024-06-28)

**Comment by vdice** [comment]
Hello @xiaocode,

The failures you are seeing are due to Spin's login client attempting to ensure a secure https connection with the local private registries which I assume are running unsecured (eg via http).  The `spin registry login` command doesn't yet support insecure/http registries (see https://github.com/fermyon/spin/issues/1211).

However, for any local registry running via http, you can proceed in using the other `spin registry push/pull` commands without needing to authenticate.  You just need to also supply the `--insecure/-k` flag.  For example: `spin registry push docker.registry.local:5000/myapp:latest --insecure`.  Can you give that a try and let us know if you are still experiencing issues?

**Comment by xiaocode** [comment]
@vdice Thank you for your anwser.
I have tried to use `spin registry push docker.registry.local:5000/myapp:latest --insecure` and success, but I when I try to use `spin up -f` with and pass the registry reference, It shows that need the docker registry must use https to retrieve images.
I just want to use spin with local docker registry so that I can run this totally without Internet.

**Comment by rajatjindal** [comment]
the same flag `--insecure` works with spin up as well. (i just verified it)

```
spin up -f localhost:5000/myapp:latest --insecure

Serving http://127.0.0.1:3000
Available Routes:
  http-ex: http://127.0.0.1:3000 (wildcard)
Handling request to Some(HeaderValue { inner: String("http://127.0.0.1:3000/") })
```

**Comment by xiaocode** [comment]
@rajatjindal @vdice Thanks to both of you.It works now!
