### ISSUE TITLE
Add a detach flag to the `spin up` command

### ISSUE THREAD

**Issue by asteurer** [fermyon/spin#2707]
I'm wondering if adding a detach flag to the `spin up` command has been discussed? It would be a nice feature to be able to run multiple Spin apps in the background without having to spawn a new shell. If it was decided that this is a good idea, we would also need to have the ability to `list` Spin processes and `stop` Spin processes.

**Comment by endocrimes** [comment]
@asteurer FWIW there are a few other ways to achieve the same with `Job Control` in your shell (https://bash.cyberciti.biz/guide/Putting_jobs_in_background). Although I tend to prefer opening a few split panes to be able to quickly see if something is throwing errors etc.

**Comment by lann** [comment]
This kind of feature falls into the "simple to prototype followed by infinite complexity" bucket, which is why there are already many dedicated tools for this sort of thing: `systemd`, `nomad` (:nerd_face:), `supervisord` (:older_adult:), etc. I would want a very specific reason why this feature _needs_ to live within Spin before adding it, though it certainly could be a 3rd-party plugin!
