### ISSUE TITLE
default feature flag values for `spin bindle push`

### ISSUE THREAD

**Issue by bacongobbler** [fermyon/spin#349]
If I perform the following

```
$ spin bindle push
error: The following required arguments were not provided:
    --file <APP_CONFIG_FILE>
    --bindle-server <BINDLE_SERVER_URL>
```

A few questions popped up into my mind:

1. should the default value of `--file` be spin.toml similar to `spin up`?
2. Should the default value of `--bindle-server` be `http://localhost:8080/v1`?

Same for `spin bindle prepare`: should `--staging-dir` default to a staging directory similar to `spin bindle push`?

**Comment by itowlson** [comment]
Agree `--file` should default.

I'm not enthusiastic about defaulting `--staging-dir` because it's not obvious what it should be.  `push` uses a temporary directory which it cleans up afterwards, but that doesn't work for `prepare` because the whole purpose of doing a prepare instead of a push is that you have access to the standalone bits - so you need to know where they are, and likely want to control where they go.

I'm also dubious about defaulting `--bindle-server`.  The trouble is that if you forget to specify it - and _aren't_ pushing locally - you'll now end up with a cryptic "connection refused" message rather than a "you forgot to tell us which server" message.  Maybe that's obvious enough - after all, it's the same as you'd get if you entered the wrong URL - but if you're explicitly specifying the URL it at least forced you to think about it.  Dunno.
