### ISSUE TITLE
`spin deploy` without -k causes blocking error

### ISSUE THREAD

**Issue by bacongobbler** [fermyon/spin#501]
```
><> spin deploy
thread 'main' panicked at 'Unable to log into Hippo: error in reqwest: error sending request for url (https://localhost:5309/api/account/createtoken): error trying to connect: error:0A000086:SSL routines:tls_post_process_server_certificate:certificate verify failed:../ssl/statem/statem_clnt.c:1883: (self-signed certificate)', /home/bacongobbler/code/spin/src/commands/deploy.rs:244:23
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

><> spin deploy -k
thread 'main' panicked at 'Unable to create and push bindle from Spin app: Failed to push bindle to server

Caused by:
    Bindle spin-hello-world/1.0.0 already exists on the server', /home/bacongobbler/code/spin/src/commands/deploy.rs:110:14
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

This occurs because `spin deploy` will happily push the invoice to bindle, but then it will not update Hippo. This is because Bindle is listening for HTTP requests while Hippo is listening for HTTPS requests, and I do not have my local certificate chain set up properly.

In this case, I've pushed the invoice to Bindle but due to a configuration mismatch, I cannot proceed. IMO `spin deploy` should catch the "already exists" error and either continue or prompt the user if they wish to proceed, possibly with some information about the module they are about to deploy.

**Comment by michelleN** [comment]
There was a recent change in Spin that does not allow Spin to push a bindle if it already exists on the server. This is the relevant PR: https://github.com/fermyon/spin/pull/459 

It's be nice to use a hash (hash of the generated invoice) as the tag/version of the bindle so we can push if there are actual changes to the app. Otherwise, we can use the bindle that already exists. Would Hippo support that kind of tag? I probably need to look and see if Bindle even supports that kind of workflow.

**Comment by michelleN** [comment]
I think this issue contains a few different topics we might want to split out.

**Comment by bacongobbler** [comment]
I believe Hippo would indeed support that kind of tag. The `ChannelRevisionSelectionStrategy` might not, but if we're using the `UseSelectedRevision` strategy, we're golden

**Comment by itowlson** [comment]
@michelleN What's the context of the 'already exists' issue?  Is it a problem for redeploying the _same_ bindle (in which case we can try to make the error checking smarter), or is it for when you deploy a _new_ bindle but don't change the revision (in which case the error is unavoidable because Bindle doesn't allow this)?

**Comment by michelleN** [comment]
It is the latter case @itowlson. The deploy logic was temporarily taking advantage of the bindle server allowing multiple post requests with the same bindle version.

**Comment by michelleN** [comment]
@bacongobbler I saw that I don't need to use the -k flag anymore on spin. Do you know what changed?

**Comment by bacongobbler** [comment]
We stopped serving things over HTTPS. Everything's over HTTP now

**Comment by michelleN** [comment]
Thank you! Closing this issue now.
