### ISSUE TITLE
How to config the redis trigger in the http trigger context

### ISSUE THREAD

**Issue by miketang84** [fermyon/spin#572]
Hi, I read the document: https://spin.fermyon.dev/rust-components/, there is a phrase:

```
This HTTP component can be paired with a Redis component, triggered on new messages on the messages Redis channel.
```

But there is only one trigger config item in the application level, so how to understand this sentence and how to config this feature, because I want to build an application which simultaneously requires http component and redis component.

Thank you.

**Comment by radu-matei** [comment]
Hi, @miketang84!
You are right, that particular phrase is a bit loose, apologies.. (a `git blame` reveals I am to blame here).

You currently cannot have an application that contains two separate component types / triggers.
We hope to solve this in the future (#40) but currently, you need two separate applications in order to achieve this.

**Comment by miketang84** [comment]
Got, thank you.
