### ISSUE TITLE
Bug: spin deploy doesn't appear to update the app with the correct bindle ID

### ISSUE THREAD

**Issue by vdice** [fermyon/spin#680]
I'm seeing incorrect and indeterministic behavior when using `spin deploy` (spin built from HEAD as of writing; `spin 0.4.0 (10fb784 2022-08-10)`).  I've installed the Fermyon platform using the [AWS Quickstart](https://www.fermyon.dev/quickstart-aws).

### Issue
When following the [docs on re-deploying a Spin app](https://github.com/fermyon/installer/blob/main/deploy.md#deploying-new-versions-of-your-app), `spin deploy` doesn't appear to properly update the app's Nomad job.  I've seen it update properly once, but repeated cycles of `1. make code change, 2. spin build, 3. spin deploy` more often than not deploys the app at an incorrect revision.  _Note: see the Workaround section below for how to avoid this behavior pending a fix._

Here's an annotated flow:

1. Build/deploy from stock [http-rust](https://github.com/fermyon/spin/tree/main/templates/http-rust/content) template.
    ```
    $ spin deploy
    http://bindle.34.228.120.147.sslip.io/v1 is responding slowly or not responding...

    Deployed http-rust version 0.1.0+q4c5e666
    Available Routes:
      http-rust: http://spin-deploy.http-rust.hippo.34.228.120.147.sslip.io/hello

    $ curl http://spin-deploy.http-rust.hippo.34.228.120.147.sslip.io/hello
    Hello, Fermyon
    ```
    Looking good 👍 

    Nomad job is running the `http-rust/0.1.0+q4c5e666` bindle, just like the output reports.

2. Make code change (update response to `Hello, Fermyon!`)
    ```
    $ spin build
    Executing the build command for component http-rust: cargo build --target wasm32-wasi --release
      Compiling http-rust v0.1.0 (/Users/vdice/go/src/github.com/fermyon/spin/examples/http-rust/http-rust)
        Finished release [optimized] target(s) in 0.44s
    Successfully ran the build command for the Spin components.

    $ spin deploy
    Deployed http-rust version 0.1.0+qa5d5da6
    Available Routes:
      http-rust: http://spin-deploy.http-rust.hippo.34.228.120.147.sslip.io/hello

    $ curl http://spin-deploy.http-rust.hippo.34.228.120.147.sslip.io/hello
    Hello, Fermyon!
    ```
    Looking good 👍 

    Nomad job is running the `http-rust/0.1.0+qa5d5da6` bindle, just like the output reports.

3. Make code change (update response to `Howdy, Fermyon!`)
    ```
    $ spin build
    Executing the build command for component http-rust: cargo build --target wasm32-wasi --release
      Compiling http-rust v0.1.0 (/Users/vdice/go/src/github.com/fermyon/spin/examples/http-rust/http-rust)
        Finished release [optimized] target(s) in 0.35s
    Successfully ran the build command for the Spin components.

    $ spin deploy
    http://hippo.34.228.120.147.sslip.io is responding slowly or not responding...

    Deployed http-rust version 0.1.0+q373881c
    Available Routes:
      http-rust: http://spin-deploy.http-rust.hippo.34.228.120.147.sslip.io/hello

    $ curl http://spin-deploy.http-rust.hippo.34.228.120.147.sslip.io/hello
    Hello, Fermyon
    ```
    Not looking good ❌ 

    Nomad job is running the `http-rust/0.1.0+q4c5e666` bindle from our first deploy, different from the output above which mentions the new/correct bindle of `0.1.0+q373881c` 

3. Make code change (update response to `foo`; losing ideas)
    ```
    $ spin build
    Executing the build command for component http-rust: cargo build --target wasm32-wasi --release
      Compiling http-rust v0.1.0 (/Users/vdice/go/src/github.com/fermyon/spin/examples/http-rust/http-rust)
        Finished release [optimized] target(s) in 0.34s
    Successfully ran the build command for the Spin components.

    $ spin deploy
    Deployed http-rust version 0.1.0+qf354d23
    Available Routes:
      http-rust: http://spin-deploy.http-rust.hippo.34.228.120.147.sslip.io/hello

    $ curl http://spin-deploy.http-rust.hippo.34.228.120.147.sslip.io/hello
    Hello, Fermyon!
    ```
    Not looking good ❌ 

    Nomad job is running the `http-rust/0.1.0+qa5d5da6` bindle from the second deploy, different from the output above which mentions the new/correct bindle of `0.1.0+qf354d23`

This behavior continues, ie although `spin deploy` appears to build and push a new bindle ID per the updated app changes, the actual Nomad job more often than not does _not_ run with the correct/intended bindle.

### Workaround
If the app's version is updated on every code change (say, v0.1.0 to v0.1.1), Hippo will be able to determine and use the most recently built/deployed version (see background details in https://github.com/fermyon/spin/issues/680#issuecomment-1211424838).

**Comment by vdice** [comment]
I see we have a PR in Spin that updates to use the latest release of Hippo: https://github.com/fermyon/spin/pull/678.  I'll give this a whirl to see if the behavior continues.

**Comment by bacongobbler** [comment]
I have a hunch why this happens.

`spin deploy` appends version build metadata to the version number. For example, `0.1.0` in spin.toml becomes `0.1.0+qf354d23`.

When Hippo is told to [use a wildcard range rule](https://github.com/fermyon/spin/blob/10fb784060a473aba7e3fc8fc226ddb6e6f4fc1a/src/commands/deploy.rs#L180-L181), Hippo [sorts revisions](https://github.com/deislabs/hippo/blob/f3ea1c826421006458e087305bd228b2d738c489/src/Application/Revisions/Queries/RevisionItem.cs#L30-L32) using semantic versioning. semver.org declares [two versions with differing build metadata](https://semver.org/#spec-item-10) have the same precedence.

If this is indeed the root cause, there are two ways to fix this:

1. Change the "build metadata" to a "pre-release" which is timestamped. That way semver libraries can sort them in a deterministic order.
2. Give Hippo a more restrictive range rule - one that matches the version number exactly (`0.1.0+qf354d23`). Update the range rule on each call to `spin deploy`.

**Comment by vdice** [comment]
Thanks @bacongobbler.  I'm inclined to favor either of the latter two options in this case (though wouldn't be opposed to also adding a timestamp at some point as this isn't necessarily mutually exclusive).  For this `spin deploy` scenario where a specific bindle ID is known, it makes sense to me to have Hippo update the app with this exact revision, rather than having Hippo attempt to sort/order.

**Comment by vdice** [comment]
A quick note to mention I've added a 'Workaround' section to the OP to inform users how to avoid this behavior pending the fix.

**Comment by kate-goldenring** [comment]
I can take this one on. @vdice what is the "OP"?:
> A quick note to mention I've added a 'Workaround' section to the OP to inform users how to avoid this behavior pending the fix.

**Comment by vdice** [comment]
> @vdice what is the "OP"?

Oops, Original Post aka the issue description above.

**Comment by kate-goldenring** [comment]
I have been debugging this a little with the goal of specifying `ChannelRevisionSelectionStrategy::UseSpecifiedRevision` when creating a channel in `spin_deploy` and am having issues discerning how to get a revision id for an recently pushed bindle. I noticed that the hippo openapi schema [requires that a revision id](https://github.com/fermyon/hippo-openapi/blob/b85cd380f1feb086e9a27e2526f49db798ead530/swagger.json#L1577) is a fully formed UUID; however, when logging app information, the `active_revision_number` is the SemVer version of the bindle.

For example, when going to redeploy the spin app, I logged the [previously deployed app](https://github.com/fermyon/spin/blob/f57cf9f7b6c72956ce457a39fedccc2807573e9a/src/commands/deploy.rs#L256), to get a sense of what id information it contained. I got the following output:
```
AppsVm { apps: [AppDto { id: "d8e40f43-f34d-4580-8bcd-687d2187e334", name: "hello-fermyon", storage_id: "hello-fermyon", description: Some("hello world app"), channels: [AppChannelSummary { id: "46b6873c-5000-40d6-833c-700ae1255a59", name: "spin-deploy", active_revision_number: Some("0.1.0+qd6bf860") }] }] }
```
**Note: `active_revision_number: Some("0.1.0+qd6bf860")`**
This made me think I could put the latest pushed bindle's version as the revision ID when calling [`add_channel` call during `spin_deploy`](https://github.com/fermyon/spin/blob/f57cf9f7b6c72956ce457a39fedccc2807573e9a/src/commands/deploy.rs#L176). However, doing so resulted in the following error -- I'm guessing because it is not a UUID:
```
One or more validation errors occurred. {"$.activeRevisionId": ["The JSON value could not be converted to System.Nullable`1[System.Guid]. Path: $.activeRevisionId | LineNumber: 0 | BytePositionInLine: 147."], "command": ["The command field is required."]}
```
Specifically, I changed the channel creation from:
```
        let channel_id = Client::add_channel(
            &hippo_client,
            app_id,
            String::from("spin-deploy"),
            None,
            ChannelRevisionSelectionStrategy::UseRangeRule,
            Some(bindle_id.version_string()),
            None,
            None,
        )
        .await
        .context("Problem creating a channel in Hippo")?;
```
To use the bindle version value for the active revision id:
```
        let channel_id = Client::add_channel(
            &hippo_client,
            app_id,
            String::from("spin-deploy"),
            None,
            ChannelRevisionSelectionStrategy::UseSpecifiedRevision,
            None,
            Some(bindle_id.version_string()),
            None,
        )
        .await
        .context("Problem creating a channel in Hippo")?;
```

Do we have an example or test of when a channel has been created using `ChannelRevisionSelectionStrategy::UseSpecifiedRevision`? 

It seems like the `id` portion of the `AppChannelSummary` is what may be needed, but that value does not seem to exist yet rather seems to be created by Hippo when deploying the app.

Any ideas @bacongobbler @vdice ? I looks like we are [already doing strategy 2](https://github.com/fermyon/spin/blob/f57cf9f7b6c72956ce457a39fedccc2807573e9a/src/commands/deploy.rs#L182) mentioned in https://github.com/fermyon/spin/issues/680#issuecomment-1211424838.

**Comment by kate-goldenring** [comment]
Update: I think i should be able to get the revision ID from the aptly named `Client::list_revisions(&hippo_client).await?;`

**Comment by vdice** [comment]
@kate-goldenring Thanks for the detailed updates here; very helpful.  I'm also feeling a bit confused by what seems to be an overloading of the term `revision`.  We'll have to get a definitive statement from @bacongobbler once he is back, but I _think_ we may be dealing with the following:

1. Hippo uses a "revision ID" (type: UUID) to track deployed revisions of an app (eg `46b6873c-5000-40d6-833c-700ae1255a59`)
2. Hippo also tracks "active_revision_number" (type: string) which appears to be the bindle version associated with an app (eg `0.1.0+qd6bf860` where the full bindle ID for an app named `hello-fermyon` would be `hello-fermyon/0.1.0+qd6bf860`)

I wonder if the attempt to supply `Some(bindle_id.version_string())` as the argument for the `active_revision_id` parameter on the `add_channel()` method is where we're being led astray (i.e., hippo is expecting a value representing the revision corresponding to use 1. above, which as you've mentioned, is probably only known after deploy).

What if we supply `Some(bindle_id.version_string())` as the argument for the `range_rule` parameter instead?

Note how previously our selection strategy and range rule was:
```
            ChannelRevisionSelectionStrategy::UseRangeRule,
            Some(bindle_id.version_string()),
```
Now I wonder if we want this pair:
```
            ChannelRevisionSelectionStrategy::UseSpecifiedRevision,
            Some(bindle_id.version_string()),
```
(and in both cases, continue to leave the next argument (`active_revision_id`) as `None`)

Worth a try anyways -- if you haven't already :)

**Comment by kate-goldenring** [comment]
@vdice I did try that. It errors with `One or more validation errors occurred. {"RevisionSelectionStrategy": ["ActiveRevisionId and the specified ChannelRevisionSelectionStrategy do not match up."]}`. I believe that using `ChannelRevisionSelectionStrategy::UseSpecifiedRevision` requires an `active_revision_id` to be set [based on how channels are created in Hippo](https://github.com/deislabs/hippo/blob/22c301461942391cd3ec68e0aa21b29f83d73cd2/src/Application/Channels/Commands/CreateChannelCommand.cs#L112) (and `ChannelRevisionSelectionStrategy::UseRangeRule` pairs with `range_rule` -- maybe instead of both `range_rule` and `active_revision_id` parameters there should be one `strategy_specifier` param).
