### ISSUE TITLE
Update Bindle dependency to latest stable release

### ISSUE THREAD

**Issue by radu-matei** [fermyon/spin#689]
ref #180, #191

Currently in Spin we are using Bindle v0.8.0.
There is a [new release candidate for Bindle](https://github.com/deislabs/bindle/releases/tag/v0.9.0-rc.1) that would help us address #180 — however, in updating it we will encounter a few breaking changes, most notably required signing of packages when publishing, and verification when pulling (see release notes).

This issue tracks the upgrade.

**Comment by FrankYang0529** [comment]
I would like to take this issue. May you assign it to me? Thank you!

**Comment by vdice** [comment]
Spin is moving towards using OCI registries as its default form of artifact support. Full details can be seen in [SIP-008: Using OCI Registries](https://github.com/fermyon/spin/blob/main/docs/content/sips/008-using-oci-registries.md).

As we'll be devoting engineering effort to the aforementioned and due to the non-trivial impact of upgrading Bindle to the next release (which is still pending and does add breaking changes), I'd propose we close this issue -- or at least make it clear that Spin will most likely stay pinned to the 0.8.x Bindle version for the foreseeable future.
