### ISSUE TITLE
`spin deploy` with `http-rust` template fails

### ISSUE THREAD

**Issue by n-tucker** [fermyon/spin#782]
Hello,

This is an awesome project that I'm thrilled to have learnt about! So many thanks on my end for putting this together ❤️ 

I was running through the docs and managed to get the template app working with `spin up`. However when I try deploy to my local instance of Fermyon using `spin deploy` I get an EOF error. Below is a screenshot from creating the app to the failed deployment
![image](https://user-images.githubusercontent.com/8991772/191657543-b940d883-883e-438e-b6db-c55b78e2d954.png)

My local instance of Fermyon is running correctly, and Nomad reports that all jobs are green. I believe the build warning is due to `cargo build` taking in a git reference from `spin-sdk`, but I'm fairly sure this has no impact

I haven't seen this reported before, so I'd appreciate any assistance on this. TIA!

**Comment by itowlson** [comment]
Possibly silly check: have you created an account on your Fermyon instance's Hippo server, and provided the appropriate username and credential environment variables?  I'm wondering if we're incorrectly trying to parse an error response where there's no body.

**Comment by charliermarsh** [comment]
(Just hit the same thing -- will check the suggested fix now.)

**Comment by charliermarsh** [comment]
My `$HIPPO_USERNAME` and `$HIPPO_PASSWORD` are set locally and I was able to login to my Fermyon instance. Once logged in, I didn't see any apps, but clicking "Add" showed me this:

<img width="743" alt="Screen Shot 2022-09-23 at 9 29 18 AM" src="https://user-images.githubusercontent.com/1309177/191971174-6d609cf0-85b6-4c99-9dcd-7e9d2186e7c3.png">

I created a "Hello" app from my `hello-fermyon-aws` storage through the UI:

<img width="753" alt="Screen Shot 2022-09-23 at 9 30 00 AM" src="https://user-images.githubusercontent.com/1309177/191971272-f47058a2-7951-4e1b-81ba-f5b32b56fffe.png">

I can now click through to the active revision but the URL is a bit strange (may be unrelated!):

<img width="868" alt="Screen Shot 2022-09-23 at 9 30 46 AM" src="https://user-images.githubusercontent.com/1309177/191971397-e8dae4a7-c3d0-448b-9268-bbc521585e9e.png">

However, `spin deploy` still fails for me, in the same way.

**Comment by charliermarsh** [comment]
(Happy to provide any other useful details.)

**Comment by n-tucker** [comment]
Apologies for the delayed response. I checked my `$HIPPO_USERNAME` and `$HIPPO_PASSWORD` and they were both set correctly. I didn't see any extra logs when setting `RUST_LOG`

Had the exact same experience as Charlie too; I can upload my app via the Hippo UI without issues

**Comment by itowlson** [comment]
@charliermarsh @n-tucker `spin deploy` is a two stage operation: first it pushes the application (manifest, code and assets) to the Bindle storage server, then notifies Hippo to create an application/endpoint that surfaces that bindle.  Your description of successfully creating the app from the Hippo UI makes me think `spin deploy` successfully created the _bindle_ - so your stuff was already in bindle storage when you logged into the Hippo UI - but didn't create the application/endpoint.  Does that sound right?  That is, am I right in thinking you didn't need to manually upload your Wasm module, etc., in order to create the app in the Hippo UI?

**Comment by charliermarsh** [comment]
Yes that's right -- I didn't need to upload my Wasm module manually.

**Comment by itowlson** [comment]
Thanks - I'm spinning up a test environment to see if I can reproduce the issue but this nails it down to the Hippo API stage if I can't!  I'll get back to you shortly.

**Comment by itowlson** [comment]
It looks like the Hippo API is sending a login failure response which is being surfaced by the Hippo Rust library as an empty error.  The cryptic error is because we expect the error to be JSON.  Possibly some revisions are out of sync - will keep digging.

**Comment by itowlson** [comment]
When trying to log in, the URL that Spin hits (`/api/auth-tokens`) that is 404ing.  So I'm guessing the client libraries are out of sync with the server...?

**Comment by itowlson** [comment]
Hi @n-tucker and @charliermarsh,

What's happened is that the Hippo API changed in Hippo 0.19, and Spin was updated to that, but the installer stayed on Hippo 0.17.  So Spin was hitting an endpoint defined in the new API, which didn't exist on the old version.  And because Spin wasn't expecting a 404, it assumed any error response would contain a JSON message... so the error of trying to parse an empty body swamped any message that might have helped resolve this quicker.

https://github.com/fermyon/installer/pull/105 contains an update to the installer that should fix your problem.  We'll also take a look at how we can update the error handling to avoid such cryptic messages in future, and at  better ways of keeping everything in sync.

Thanks for letting us know about this and for helping us work through the details.

**Comment by n-tucker** [comment]
Happy days, glad to be of assistance and thanks again for looking into this! 😄
