### ISSUE TITLE
Plan for Spin Wasm interface migrations

### ISSUE THREAD

**Issue by lann** [fermyon/spin#873]
We know we will be migrating from the pre-component wit-bindgen ABI to the component canonical ABI "soonish". We expect to later make various breaking changes to trigger and host component interfaces, especially as new Wasm features stabilize (resources, async, streams, future WASI versions, etc).

**Comment by lann** [comment]
Initial thoughts:

- For the ABI change, support both ABIs for "a while", issuing deprecation warnings in Spin for a release or two before removing the old ABI. If we can figure out a reasonable way to wrap the new ABI in an adapter component, great.
- For future interface changes, write an adapter component for each breaking change and have Spin (`spin build`? `up`?) wrap old components with those as needed. If we can have a nice generic mechanism for this it could make updates relatively painless.

**Comment by itowlson** [comment]
For future interface changes, I was wondering about the practicality of versioning the interfaces e.g. `redis-1.0`, `redis-2.0`, etc., which would provide some explicitness and provide for meaningful detection and diagnostics.  I'm particularly thinking about Wasm components built against old interfaces and deployed to Cloud: we'd like them to get something like "Fermyon Cloud no longer supports `foo-1.0`, please rebuild against..." rather than "link error, required import `bar` not found".  (Needless to say, any implementation would indeed lean heavily on adapters - this is more about how we _detect and diagnose_ a mismatch.)

Looking at Luke's Wasm Day presentation, though, he doesn't show any versioning of interfaces there.  But I feel like issuing new WITs with the same name but different members is going to lead to confusion long term.  Is versioning being covered in the component model discussions, and if so what is the thinking?

**Comment by lann** [comment]
> Is versioning being covered in the component model discussions, and if so what is the thinking?

I don't know that it has been formalized anywhere but my understanding is that breaking changes would at least conventionally involve a change to the interface name. @fibonacci1729 @dicej

**Comment by lann** [comment]
I've been looking at how best to support the "old" ABI. The least-bad option at this point seems to be to fork wit-bindgen at tag v0.2.0 and update wasmtime there. Assuming that works out in the short term I think we can stick with that strategy until/unless it becomes a maintenance burden at which point we can reevaluate.

**Comment by dicej** [comment]
BTW, we discussed component interface versioning recently with Luke and others, and there was consensus that we'll want more than just a naming convention, and that each interface the component imports or exports should be explicitly versioned.  The details of how that is represented in the tooling (e.g. inside the WIT files themselves vs. in metadata elsewhere) are yet to be determined, however.

**Comment by lann** [comment]
WIT packages now include a semver version, which will help here.

**Comment by lann** [comment]
This is mostly irrelevant now due to spin-componentize.
