### ISSUE TITLE
--follow doesn't validate provided values

### ISSUE THREAD

**Issue by etehtsea** [fermyon/spin#944]
### Current behaviour
Spin accepts invalid component ids as an input.

### Expected behaviour
Spin fails with error if provided component id is invalid.

### Example

```sh
spin/examples/http-rust-outbound-http main $  ../../target/debug/spin build --up --follow rust-outbound-http,rust-outbound-http-wildcard
<..>
Serving http://127.0.0.1:3000
Available Routes:
  rust-outbound-http: http://127.0.0.1:3000/outbound
  rust-outbound-http-wildcard: http://127.0.0.1:3000/wildcard
```

The example about should fail because `--follow rust-outbound-http --follow rust-outbound-http-wildcard` is expected instead.

Other examples:

```
--follow ""
--follow ust-outbound-http
```

**Comment by itowlson** [comment]
@lann I had a quick look at this and I'm not quite sure where to tackle it.  The `follow` arguments are declared on the `trigger` CLI, not on `up`, so we can't readily validate them in that initial load phase; and in `trigger` the component level of the application doesn't seem to easily available outside of `builder.build` which feels like the wrong place to do validation.  Do you have any suggestions on where would be a suitable place to perform this check?

**Comment by lann** [comment]
Yeah, the code flow is confusing in there because of ordering requirements in setting up the underlying wasmtime `Engine` and `Linker`. I ended up adding `TriggerHooks` to deal with this sort of thing, which is actually already being used for `follow`; you should be able to add a check right here: https://github.com/fermyon/spin/blob/a9a9adabb00108c2b9641e7d48b43d08a424d501/crates/trigger/src/stdio.rs#L71

**Comment by itowlson** [comment]
Aha, thanks!
