### ISSUE TITLE
delete and redeploy of same app sometimes uses old revision

### ISSUE THREAD

**Issue by rajatjindal** [fermyon/spin#955]
i tried deleting (from the UI) and redeploying my app on Fermyon cloud and sometimes it seems to be serving old revision (until I deploy the app 2nd time).

**Comment by itowlson** [comment]
Does #870 affect this?  I saw there was a lengthy chat thread, are there any additional details or conclusions that are worth capturing here?

**Comment by rajatjindal** [comment]
just that we were able to theoretically narrow down issue to this line here: https://github.com/fermyon/spin/blob/4f2251244fa17f36abca899bb3e775ae718aa45f/src/commands/deploy.rs#L274

may be @kate-goldenring can add more meaningful insights here.

**Comment by kate-goldenring** [comment]
We are using `UseRangeRule` when an app is being created and `UseSpecifiedRevision` when an app is being modified (redeployed with changes). Since a revision does not exist until an app is created, `UseRangeRule` is used to have Cloud select a revision. Then, on updates, `deploy` queries for an app and uses the existing revision to deploy the changes to. There may be some race case here where the old revision is not being cleaned up so we are seeing it and using it rather than creating a new revision with a `UseRangeRule`.

**Comment by kate-goldenring** [comment]
[Here](https://github.com/fermyon/spin/blob/859d7f5aef47dc20d7836160255c4bb1f2f1a7c0/src/commands/deploy.rs#L226) is where we check in `deploy.rs` if the app exists. [This call to get existing apps](https://github.com/fermyon/spin/blob/859d7f5aef47dc20d7836160255c4bb1f2f1a7c0/src/commands/deploy.rs#L462) may be incorrectly returning the app that was deleted causing that revision to be reused rather than creating a new one.

**Comment by kate-goldenring** [comment]
@rajatjindal did this cause any user errors? I dont see it affecting the user experience but it is a clear inconsistency that could cause problems in the future and probably makes testing/data gathering inconsistent

**Comment by rajatjindal** [comment]
if a user deletes and recreates the app, he will see old version of his app running, which IMO will confuse the end user. 

I was able to verify this by deploying an app with small changes, and on 3rd attempt, it reused the version from 1st attempt and therefore ran the old code.

**Comment by rajatjindal** [comment]
I believe what is happening is that during create app command, we trigger `Import Revisions` command which imports all existing revisions from `bindle` using the `storageId` and associates them with the current app id

and now when we try to deploy  using ‘Range Rule’, it picks up the random version  from that list of revisions and deploy that.

but because we already have bindle_id during `deploy` command, we can get the `active-revision-id` as follows and then call `add_channel` with specific version.

```
 let active_revision_id = self
                    .get_revision_id_cloud(&client, bindle_id.version_string().clone(), app_id)
                    .await?;
```

**Comment by rajatjindal** [comment]
i was able to verify this by using patched `spin` to deploy and it seems to be working as expected.

**Comment by rajatjindal** [comment]
i am still  trying to see if there is a better way to fix this. will report back
