### ISSUE TITLE
`spin templates update` should try to update all known templates

### ISSUE THREAD

**Issue by rawkode** [fermyon/spin#990]
Just upgraded to 0.7.0 and `spin add` didn't work, which I figured would be because the templates needed updating too.

Updating from there should be `spin templates update`, however at present we need to run:

`spin templates install --git https://github.com/fermyon/spin --update`

**Comment by itowlson** [comment]
This also relates to https://github.com/fermyon/spin/issues/947, in that both of these would require us to track where templates came from (which we don't do at the moment).

If we did that, then rather than requiring the user to run a command, I'd be inclined to detect when templates were mismatched and offer to update at that point, e.g.

```
$ spin new http-rust foo
You are using Spin 0.9 but your templates are for Spin 0.7. Would you like to update your templates?
> Update templates to 0.9
  Leave templates at 0.7
```

(This doesn't preclude having an update command as well.)

**Comment by michelleN** [comment]
@itowlson - How could we track what spin version templates are compatible with?
